version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 35
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: true
      check-blank: false
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 160
      statements: 70
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 4
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - style
        - opinionated
        - performance
      settings:
        rangeValCopy:
          sizeThreshold: 1024
    gocyclo:
      min-complexity: 35
    govet:
      enable-all: false
    lll:
      line-length: 180
      tab-width: 8
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 8
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          envconfig: upper
          firestore: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: camel
        use-field-name: false
    unparam:
      check-exported: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'shadow: declaration of "err" shadows declaration'
      - path: (.+)\.go$
        text: 'shadow: declaration of "ctx" shadows declaration'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/creack/pty
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
